-- ─────────────────────────────────────────────────────────────────────────────
-- ZapAI — Seed Script
-- Clean database state: all mock data removed.
-- Real merchants, products, negotiation mandates, and orders are created by users.
-- ─────────────────────────────────────────────────────────────────────────────
