import { Product, ConversationThread, Order, AnalyticsSummary, ActivityEvent, NegotiationRules, AgentProfile, MerchantProfile } from "../types";

export const initialMockProducts: Product[] = [
  {
    id: "prod_1",
    storeId: "store_runfast",
    title: "Nike Air Zoom Pegasus 40",
    sku: "NK-PEG-40-BLK",
    price: 3999,
    inventory: 18,
    provider: "AGENTBRIDGE",
    aiSellingEnabled: true,
    minPrice: 3500,
    maxDiscountPercent: 12,
    description: "Responsive road running shoes with breathable mesh upper and dual Zoom Air units.",
    category: "Footwear",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_2",
    storeId: "store_runfast",
    title: "Adidas Ultraboost Light",
    sku: "AD-UB-LGT-WHT",
    price: 4999,
    inventory: 8,
    provider: "SHOPIFY",
    aiSellingEnabled: true,
    minPrice: 4400,
    maxDiscountPercent: 12,
    description: "Lightweight epic energy return performance running shoes with Continental rubber outsole.",
    category: "Footwear",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_3",
    storeId: "store_runfast",
    title: "Puma Nitro Velocity 3",
    sku: "PM-NV-3-BLU",
    price: 3499,
    inventory: 24,
    provider: "AGENTBRIDGE",
    aiSellingEnabled: true,
    minPrice: 2999,
    maxDiscountPercent: 15,
    description: "All-distance training running shoe with premium nitrogen-infused foam.",
    category: "Footwear",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_4",
    storeId: "store_runfast",
    title: "Asics Gel-Nimbus 26",
    sku: "AS-NB-26-GRY",
    price: 5499,
    inventory: 5,
    provider: "SHOPIFY",
    aiSellingEnabled: false,
    minPrice: 5100,
    maxDiscountPercent: 8,
    description: "Max-cushion neutral running shoes with PureGEL technology for plush landings.",
    category: "Footwear",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_5",
    storeId: "store_runfast",
    title: "RunFast Pro Hydro Hydration Vest",
    sku: "RF-HYD-VST-BLK",
    price: 1899,
    inventory: 42,
    provider: "AGENTBRIDGE",
    aiSellingEnabled: true,
    minPrice: 1599,
    maxDiscountPercent: 15,
    description: "5L lightweight breathable trail running vest with twin 500ml soft flasks included.",
    category: "Accessories",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialMockConversations: ConversationThread[] = [
  {
    id: "conv_1",
    customerPhone: "+91 98765 43210",
    customerName: "Rahul Sharma",
    lastMessage: "Payment done! Excited for the shoes.",
    lastMessageAt: "2 mins ago",
    status: "deal_closed",
    unread: false,
    dealAmount: 3799,
    productsDiscussed: ["Nike Air Zoom Pegasus 40"],
    messages: [
      {
        id: "m_1",
        conversationId: "conv_1",
        sender: "customer",
        content: "Hi! Looking for running shoes for 10k marathon training under ₹4000.",
        timestamp: "10:14 AM",
      },
      {
        id: "m_2",
        conversationId: "conv_1",
        sender: "seller_agent",
        content: "Hey Rahul! Great goal. I recommend our top-rated Nike Air Zoom Pegasus 40. Listed at ₹3,999 with dual Zoom Air units for responsive daily training. How does that look?",
        timestamp: "10:14 AM",
      },
      {
        id: "m_3",
        conversationId: "conv_1",
        sender: "customer",
        content: "Can you do ₹3600? I can buy immediately right now on UPI.",
        timestamp: "10:15 AM",
      },
      {
        id: "m_4",
        conversationId: "conv_1",
        sender: "seller_agent",
        content: "I can't go down to ₹3,600, but since you're ready to order today, I can do a special deal of ₹3,799 with free express shipping! Would you like me to lock this price for you?",
        timestamp: "10:15 AM",
        metadata: { offerAmount: 3799 },
      },
      {
        id: "m_5",
        conversationId: "conv_1",
        sender: "customer",
        content: "Sounds fair, send me the payment link.",
        timestamp: "10:16 AM",
      },
      {
        id: "m_6",
        conversationId: "conv_1",
        sender: "seller_agent",
        content: "Here is your exclusive Razorpay secure link for ₹3,799: https://rzp.io/i/plink_runfast_78492. Reserved for 15 minutes!",
        timestamp: "10:16 AM",
        metadata: {
          isPaymentLink: true,
          paymentLinkId: "plink_runfast_78492",
          offerAmount: 3799,
        },
      },
      {
        id: "m_7",
        conversationId: "conv_1",
        sender: "customer",
        content: "Payment done! Excited for the shoes.",
        timestamp: "10:18 AM",
      },
      {
        id: "m_8",
        conversationId: "conv_1",
        sender: "system",
        content: "Razorpay payment ID pay_Qx89KkLp9 captured (₹3,799.00 via UPI). Order #RF-1049 confirmed.",
        timestamp: "10:18 AM",
      },
    ],
    traces: [
      {
        id: "t_1",
        title: "Intent Detected",
        detail: "Customer looking for 10k running shoes with budget constraint < ₹4,000",
        status: "completed",
        timestamp: "10:14:02 AM",
        durationMs: 42,
      },
      {
        id: "t_2",
        title: "Catalog Search Tool Executed",
        detail: "Matched 'Nike Air Zoom Pegasus 40' (Match score: 0.94, In Stock: 18)",
        status: "completed",
        timestamp: "10:14:03 AM",
        durationMs: 110,
      },
      {
        id: "t_3",
        title: "Negotiation Mandate Check",
        detail: "Customer offer: ₹3,600 (10% discount request). Mandate rule allows max 12% off (Floor ₹3,500). Counter-offer computed at ₹3,799 (5% off).",
        status: "completed",
        timestamp: "10:15:10 AM",
        durationMs: 65,
      },
      {
        id: "t_4",
        title: "Inventory Reservation",
        detail: "SKU NK-PEG-40-BLK locked for 15 mins (Reservation ID: res_9041)",
        status: "completed",
        timestamp: "10:16:01 AM",
        durationMs: 88,
      },
      {
        id: "t_5",
        title: "Razorpay Payment Link Generated",
        detail: "Created plink_runfast_78492 for ₹3,799 via Razorpay API",
        status: "completed",
        timestamp: "10:16:04 AM",
        durationMs: 195,
      },
      {
        id: "t_6",
        title: "Webhook Payment Verified",
        detail: "Signature verified: payment.captured event processed. Order RF-1049 created.",
        status: "completed",
        timestamp: "10:18:12 AM",
        durationMs: 34,
      },
    ],
  },
  {
    id: "conv_2",
    customerPhone: "+91 91234 56789",
    customerName: "Priya Patel",
    lastMessage: "Let me check size chart first",
    lastMessageAt: "18 mins ago",
    status: "negotiating",
    unread: true,
    dealAmount: 4699,
    productsDiscussed: ["Adidas Ultraboost Light"],
    messages: [
      {
        id: "m_21",
        conversationId: "conv_2",
        sender: "customer",
        content: "Do you have Ultraboost Light in UK 7 size in stock?",
        timestamp: "09:50 AM",
      },
      {
        id: "m_22",
        conversationId: "conv_2",
        sender: "seller_agent",
        content: "Yes Priya! We have 8 pairs in UK 7 White. Price is ₹4,999.",
        timestamp: "09:50 AM",
      },
      {
        id: "m_23",
        conversationId: "conv_2",
        sender: "customer",
        content: "Can you give 10% discount?",
        timestamp: "09:51 AM",
      },
      {
        id: "m_24",
        conversationId: "conv_2",
        sender: "seller_agent",
        content: "I can offer ₹4,699 right now!",
        timestamp: "09:51 AM",
      },
    ],
    traces: [
      {
        id: "t_21",
        title: "Inventory Checked",
        detail: "SKU AD-UB-LGT-WHT verified on Shopify Provider (8 units)",
        status: "completed",
        timestamp: "09:50:11 AM",
      },
      {
        id: "t_22",
        title: "Negotiation Evaluated",
        detail: "Offered ₹4,699 within allowable floor (₹4,400)",
        status: "completed",
        timestamp: "09:51:05 AM",
      },
    ],
  },
];

export const initialMockOrders: Order[] = [
  {
    id: "ord_1049",
    orderNumber: "RF-1049",
    customerName: "Rahul Sharma",
    customerPhone: "+91 98765 43210",
    productTitle: "Nike Air Zoom Pegasus 40 (UK 9)",
    sku: "NK-PEG-40-BLK",
    amount: 3799,
    originalPrice: 3999,
    discountApplied: 200,
    paymentStatus: "paid",
    orderStatus: "processing",
    provider: "AGENTBRIDGE",
    razorpayPaymentId: "pay_Qx89KkLp9",
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: "ord_1048",
    orderNumber: "RF-1048",
    customerName: "Vikram Mehta",
    customerPhone: "+91 98200 11223",
    productTitle: "Puma Nitro Velocity 3 (UK 8)",
    sku: "PM-NV-3-BLU",
    amount: 3199,
    originalPrice: 3499,
    discountApplied: 300,
    paymentStatus: "paid",
    orderStatus: "fulfilled",
    provider: "AGENTBRIDGE",
    razorpayPaymentId: "pay_Qv11MmZn2",
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: "ord_1047",
    orderNumber: "RF-1047",
    customerName: "Sneha Roy",
    customerPhone: "+91 97112 88441",
    productTitle: "RunFast Pro Hydro Vest",
    sku: "RF-HYD-VST-BLK",
    amount: 1699,
    originalPrice: 1899,
    discountApplied: 200,
    paymentStatus: "paid",
    orderStatus: "fulfilled",
    provider: "AGENTBRIDGE",
    razorpayPaymentId: "pay_Qt99PlKx7",
    createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
];

export const initialMockAnalytics: AnalyticsSummary = {
  agentGmv: 82490,
  gmvGrowthPercent: 28.4,
  totalConversations: 128,
  dealsClosed: 37,
  conversionRate: 91.2,
  averageDiscount: 6.8,
  averageOrderValue: 3840,
  topSellingProducts: [
    { title: "Nike Air Zoom Pegasus 40", salesCount: 19, revenue: 72181 },
    { title: "Puma Nitro Velocity 3", salesCount: 11, revenue: 35189 },
    { title: "RunFast Hydro Vest", salesCount: 7, revenue: 11893 },
  ],
};

export const initialMockActivity: ActivityEvent[] = [
  {
    id: "act_1",
    type: "PAYMENT_CAPTURED",
    title: "Payment captured via Razorpay UPI",
    description: "₹3,799 captured for Rahul Sharma (Order #RF-1049)",
    timestamp: "2 mins ago",
  },
  {
    id: "act_2",
    type: "NEGOTIATION_COMPLETED",
    title: "AI Seller closed deal at ₹3,799",
    description: "Countered ₹3,600 request with ₹3,799 + free shipping mandate",
    timestamp: "4 mins ago",
  },
  {
    id: "act_3",
    type: "INVENTORY_UPDATED",
    title: "Inventory reserved for 15m",
    description: "1 unit of NK-PEG-40-BLK locked for pending payment",
    timestamp: "5 mins ago",
  },
  {
    id: "act_4",
    type: "CONVERSATION_STARTED",
    title: "New WhatsApp lead from +91 91234 56789",
    description: "Inquiry on Adidas Ultraboost UK 7 stock availability",
    timestamp: "18 mins ago",
  },
  {
    id: "act_5",
    type: "PRODUCT_SYNCED",
    title: "Shopify catalog synchronized",
    description: "Imported 184 products with live variant inventory",
    timestamp: "1 hour ago",
  },
];

export const defaultNegotiationRules: NegotiationRules = {
  maxDiscountPercent: 12,
  minimumOrderValue: 1500,
  freeShippingAbove: 3000,
  bundleOffersEnabled: true,
  alternativeProductsEnabled: true,
  humanApprovalAbove: 10000,
  riskProfile: "balanced",
};

export const defaultAgentProfile: AgentProfile = {
  name: "RunFast Seller Agent",
  tone: "friendly",
  status: "active",
  autoNegotiationEnabled: true,
  humanEscalationEnabled: true,
  escalationThresholdAmount: 10000,
};

export const defaultMerchantProfile: MerchantProfile = {
  name: "Merchant Admin",
  email: "merchant@runfast.in",
  phone: "+91 98765 00000",
  merchantId: "merchant_01",
  storeName: "RunFast Sports",
  role: "Store Owner & Admin",
  status: "active",
};

